project_id = "egymdyuqsnhntdzupsfx"

[functions.send-payment-reminders]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.send-whatsapp-reminder]
verify_jwt = false
